### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Piercel2022** [businesskaniki/Leaderboard#5]
Good job so far! :tada: 
There are some issues that you still need to work on to go to the next project but you are almost there! 
![ ](https://i.gifer.com/origin/51/511934e708e3ba76603b2ebd47d9e6cd_w200.webp)
There are some issues you have to fix in the readme file to improve your workflow:
Kindly change the directory name aflter cloning

**Comment by markotuya0** [comment]
good job on making the required changes.
